services:
 postgres:
  image: postgres:17.4
  container_name: postgres_container
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: book-store
  ports:
   - "5432:5432"
